PetStore/Models/Basket.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PetStore.Models
{
    public enum OrderPlaced
    {
        Yes, No
    }
    public class Basket
    {
        [Key]
        public int BasketId { get; set; }
        public int? Quantity { get; set; }
        [DisplayName("Order Status")]
        public OrderPlaced? OrderPlaced { get; set; }
        [DisplayName("Sub-Total")]
        public decimal? SubTotal { get; set; }
        [DisplayName("Total")]
        public decimal? Total { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("Date")]
        public DateTime? DateCreated { get; set; }
        [DisplayName("Customer Name")]
        public int? CustomerId { get; set; }
        public Customer Customers { get; set; }
        [JsonIgnore]
        public ICollection<BasketItem> BasketItems { get; set; }
        //public ICollection<Product> Products { get; set; }
    }
}

PetStore/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PetStore.Models;
using PetStore.Services;

namespace PetStore.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasket _Basket;
        private readonly ICustomer _Customer;
        public BasketController(IBasket _IBasket, ICustomer _ICustomer)
        {
            _Basket = _IBasket;
            _Customer = _ICustomer;
        }
        public IActionResult Index()
        {
            return View(_Basket.GetBaskets);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Customers = _Customer.GetCustomers;
            return View();
        }
        [HttpPost]
        public IActionResult Create(Basket model)
        {
            if (ModelState.IsValid)
            {
                _Basket.Add(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        //public int CreateBasket(Basket model) {
        //    if (ModelState.IsValid)
        //    {
        //       return  _Basket.Add(model);
        //        //return RedirectToAction("Index");
        //    }
        //    else {
        //        return 1;
        //    }
            
        //}
        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            else
            {
                return View(_Basket.GetBasket(Id));
            }
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeleteConfirm(int Id)
        {
            _Basket.Remove(Id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int? Id)
        {
            return View(_Basket.GetBasket(Id));
        }

        //customer related actions starts from here
        public IActionResult getCustomerBasket()
        {
            int Id = getBasketIdFromSession();
            ViewBag.CustomerName = getCustomerNameFromSession();
            return View(_Basket.GetBasket(Id));
        }

        private int getBasketIdFromSession()
        {
            var currentBasket = JsonConvert.DeserializeObject<Basket>(HttpContext.Session.GetString("activeBasket"));
            return Convert.ToInt32(currentBasket.BasketId);
        }
        private string getCustomerNameFromSession() {
            var loggedIn = JsonConvert.DeserializeObject<Customer>(HttpContext.Session.GetString("activeCustomer"));
            int customerID = Convert.ToInt32(loggedIn.CustomerId);
            return Convert.ToString(loggedIn.FirstName);
            
        }
        public IActionResult LoggedOut() => View();



    }
}

PetStore/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PetStore.Models;
using PetStore.Services;
using System.Web;
using Newtonsoft.Json;

namespace PetStore.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProduct _Product;
        public ProductController(IProduct _IProduct)
        {
            _Product = _IProduct;
        }
        public IActionResult Index()
        {
            return View(_Product.GetProducts);
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            Product model = new Product();
            model.ProductId = 0;
            return View(model);
        }
        //[HttpPost]
        //public IActionResult Create(Product model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _Product.Add(model);
        //        return RedirectToAction("Index");
        //    }
        //    return View(model);
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(int Id,[Bind("ProductId,ProductName,Price,Description")] Product product,IFormFile imageFile) {
            if (Id != product.ProductId)
            {
                return NotFound();
            }
            if (ModelState.IsValid) {
                try {
                    if (imageFile != null) {
                        using (var ms = new MemoryStream()) {
                            imageFile.CopyTo(ms);
                            product.ProductImage = ms.ToArray();
                        }
                         _Product.Add(product);
                    }
                } catch (Exception ex) {
                    throw;
                }
            }
            return View(product);
        }
        public IActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            else
            {
                return View(_Product.GetProduct(Id));
            }
            
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int? Id) {
            _Product.Remove(Id);
            return RedirectToAction("Index");

        }
        public IActionResult Edit(int? Id)
        {
            var model = _Product.GetProduct(Id);
            return View("create", model);
        }

        //customer side 
        public IActionResult IndexCustomer() {
            if (HttpContext.Session.GetString("activeCustomer") != null && HttpContext.Session.GetString("activeBasket")!=null)
            {
                var loggedIn = JsonConvert.DeserializeObject<Customer>(HttpContext.Session.GetString("activeCustomer"));
                int customerID = Convert.ToInt32(loggedIn.CustomerId);
                string customerName = Convert.ToString(loggedIn.FirstName);
                ViewBag.cid = customerName;

                var currentBasket = JsonConvert.DeserializeObject<Basket>(HttpContext.Session.GetString("activeBasket"));
                int BasketId = Convert.ToInt32(currentBasket.BasketId);
                ViewBag.bid = BasketId;
                return View(_Product.GetProducts);
            }
            else
            {
                
                return RedirectToAction("CustomerLogin", "Customer");
            }
                
            
           
            

            
        }
        [HttpGet]
        public IActionResult DetailsCustomer(int? Id) {
            Product model = _Product.GetProduct(Id);
            ViewBag.selectedProduct = model;

            var loggedIn = JsonConvert.DeserializeObject<Customer>(HttpContext.Session.GetString("activeCustomer"));
            int customerID = Convert.ToInt32(loggedIn.CustomerId);
            string customerName = Convert.ToString(loggedIn.FirstName);
            ViewBag.cid = customerName;

            var currentBasket = JsonConvert.DeserializeObject<Basket>(HttpContext.Session.GetString("activeBasket"));
            int BasketId = Convert.ToInt32(currentBasket.BasketId);
            ViewBag.bid = BasketId;
            


            return View(model);
        }
    }
}

PetStore/Views/Basket/Create.cshtml
@model PetStore.Models.Basket

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Basket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderPlaced" class="control-label"></label>
                <select asp-for="OrderPlaced" class="form-control"><option>Yes</option><option>No</option></select>
                <span asp-validation-for="OrderPlaced" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubTotal" class="control-label"></label>
                <input asp-for="SubTotal" class="form-control" />
                <span asp-validation-for="SubTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class="form-control" asp-items="@(new SelectList(ViewBag.Customers,"CustomerId","FirstName"))"></select>
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PetStore/Views/Basket/Delete.cshtml
@model PetStore.Models.Basket

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Basket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderPlaced)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderPlaced)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SubTotal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubTotal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BasketId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PetStore/Views/Basket/Details.cshtml
@model PetStore.Models.Basket

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Basket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderPlaced)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderPlaced)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SubTotal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubTotal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Customers)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Customers.CustomerId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BasketItems)
        </dt>
        <dd>
            @*place for basket items associated with basket*@
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Quantity
                        </th>
                        <th>
                            Product ID
                        </th>
                        <th>
                            Basket ID
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.BasketItems)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ItemQuantity)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Products.ProductName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.BasketId)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.BasketItemId">Edit</a> |
                                <a asp-action="Details" asp-route-id="@item.BasketItemId">Details</a> |
                                <a asp-action="Delete" asp-route-id="@item.BasketItemId">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.BasketId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PetStore/Views/Basket/Index.cshtml
@model IEnumerable<PetStore.Models.Basket>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderPlaced)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubTotal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderPlaced)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubTotal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customers.FirstName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BasketId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.BasketId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.BasketId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

PetStore/Views/Basket/LoggedOut.cshtml
@{
    ViewData["Title"] = "LoggedOut";
}

<h2>Thank you for shopping with Pati Online store</h2>
<a asp-area="" asp-controller="Customer" asp-action="CustomerLogin">Log-In Again</a>

PetStore/Views/Basket/getCustomerBasket.cshtml
@model PetStore.Models.Basket

@{
    ViewData["Title"] = "getCustomerBasket";
}
<style>
    a:hover{
        color:orangered;
    }
    a.navRight {
        padding: 5px;
        border: 1px solid green;
    }
</style>
<div style="margin:20px">
    <h2 style="display:inline">Basket details of @ViewBag.CustomerName </h2>
    <div style="float:right;">

        <a asp-area="" asp-controller="Product" asp-action="IndexCustomer" style="text-decoration:none" class="navRight">Continue Shopping</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a asp-area="" asp-controller="Basket" asp-action="LoggedOut" style="text-decoration:none" class="navRight">Check out</a>
    </div>
</div>
<div>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderPlaced)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderPlaced)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SubTotal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubTotal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>*@
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Customers)
        </dt>
        <dd>
            @ViewBag.CustomerName
        </dd>
        <dt>
           @* Place for basket items *@
        </dt>
        <dd>
            @* Place for basket Items start*@
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Product Name
                        </th>
                        <th>
                            Quantity
                        </th>

                        <th>
                            Unit Price
                        </th>
                        <th>
                            Total Price
                        </th>
                        <th>Basket ID</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.BasketItems)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Products.ProductName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ItemQuantity)
                        </td>

                        <td>
                            $ @Html.DisplayFor(modelItem => item.Products.Price)
                        </td>
                        <td>
                            $ @((item.ItemQuantity * item.Products.Price))
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BasketId)
                        </td>
                    </tr>
                    }
                    <tr><td><b>Total</b></td>
                        <td>@Html.DisplayFor(model => model.Quantity)</td>
                    
                    <td>$ @Html.DisplayFor(model => model.Total)</td>
                    <td>$ @Html.DisplayFor(model => model.Total)</td>
                    </tr>
                </tbody>
            </table>
            @* Place for basket Items end *@
        </dd>
    </dl>
   
</div>