PetStore/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PetStore.Models
{
    public class Product
    {
        [Key]
        public int ProductId { get; set; }
        [DisplayName("Name")]
        public string ProductName { get; set; }
        public decimal? Price { get; set; }
        public string Description { get; set; }
        public byte[] ProductImage { get; set; }
        public BasketItem basketItems { get; set; }
        
    }
}

PetStore/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PetStore.Models;
using PetStore.Services;

namespace PetStore.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasket _Basket;
        private readonly ICustomer _Customer;
        public BasketController(IBasket _IBasket, ICustomer _ICustomer)
        {
            _Basket = _IBasket;
            _Customer = _ICustomer;
        }
        public IActionResult Index()
        {
            return View(_Basket.GetBaskets);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Customers = _Customer.GetCustomers;
            return View();
        }
        [HttpPost]
        public IActionResult Create(Basket model)
        {
            if (ModelState.IsValid)
            {
                _Basket.Add(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        //public int CreateBasket(Basket model) {
        //    if (ModelState.IsValid)
        //    {
        //       return  _Basket.Add(model);
        //        //return RedirectToAction("Index");
        //    }
        //    else {
        //        return 1;
        //    }
            
        //}
        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            else
            {
                return View(_Basket.GetBasket(Id));
            }
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeleteConfirm(int Id)
        {
            _Basket.Remove(Id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Details(int? Id)
        {
            return View(_Basket.GetBasket(Id));
        }

        //customer related actions starts from here
        public IActionResult getCustomerBasket()
        {
            int Id = getBasketIdFromSession();
            ViewBag.CustomerName = getCustomerNameFromSession();
            return View(_Basket.GetBasket(Id));
        }

        private int getBasketIdFromSession()
        {
            var currentBasket = JsonConvert.DeserializeObject<Basket>(HttpContext.Session.GetString("activeBasket"));
            return Convert.ToInt32(currentBasket.BasketId);
        }
        private string getCustomerNameFromSession() {
            var loggedIn = JsonConvert.DeserializeObject<Customer>(HttpContext.Session.GetString("activeCustomer"));
            int customerID = Convert.ToInt32(loggedIn.CustomerId);
            return Convert.ToString(loggedIn.FirstName);
            
        }
        public IActionResult LoggedOut() => View();



    }
}

PetStore/Controllers/BasketItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PetStore.Models;
using PetStore.Services;

namespace PetStore.Controllers
{
    public class BasketItemController : Controller
    {
        private readonly IBasketItem _BasketItem;
        private readonly IProduct _Product;
        private readonly IBasket _Basket;
        private readonly ICustomer _Customer;
       
        //Basket pullBasket;
        public BasketItemController(IBasketItem _IBasketItem,IProduct _IProduct,IBasket _IBasket, ICustomer _ICustomer)
        {
            _BasketItem = _IBasketItem;
            _Product = _IProduct;
            _Basket = _IBasket;
            _Customer = _ICustomer;
        }
        public IActionResult Index()
        {
            
            
            return View(_BasketItem.GetBasketItems);
            
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Products = _Product.GetProducts;
            ViewBag.Baskets = _Basket.GetBaskets;
            return View();
        }
        [HttpPost]
        public IActionResult Create(BasketItem model)
        {
            if (ModelState.IsValid)
            {
                _BasketItem.Add(model);
                return RedirectToAction("Index");
            }
            return View(model);

        }
        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            else
            {
                return View(_BasketItem.GetBasketItem(Id));
            }
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeleteConfirm(int? Id)
        {
            _BasketItem.Remove(Id);
            return RedirectToAction("Index");
        }

        //front-end related
        
        public IActionResult AddToCart(int? pid,int? quantity,decimal? price) {
            if (quantity == null)
            {
                quantity = 1;
            }

            //basket item creation
            BasketItem bi = new BasketItem();
            bi.ItemQuantity = quantity;
            //bi.ItemQuantity = quantity==null?1:quantity;
            bi.ProductId = pid;
            bi.BasketId = getBasketIdFromSession(); 
            _BasketItem.Add(bi);
            //basket creation
            Basket pullBasket = new Basket() { Quantity = quantity,Total=price* quantity };
            //Basket pullBasket = new Basket() { Quantity = quantity == null ? 1 : quantity, Total = price * quantity == null ? 1 : quantity };
            _Basket.Update(bi.BasketId, pullBasket);
            //return RedirectToAction("Index");
            //return RedirectToAction("IndexCustomer", "Product");
            return RedirectToAction("getCustomerBasket", "Basket");
        }

        private int getBasketIdFromSession()
        {
            var currentBasket = JsonConvert.DeserializeObject<Basket>(HttpContext.Session.GetString("activeBasket"));
            return Convert.ToInt32(currentBasket.BasketId);
        }

        

    }
}

PetStore/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PetStore.Models;
using PetStore.Services;
using System.Web;
using Newtonsoft.Json;

namespace PetStore.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProduct _Product;
        public ProductController(IProduct _IProduct)
        {
            _Product = _IProduct;
        }
        public IActionResult Index()
        {
            return View(_Product.GetProducts);
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            Product model = new Product();
            model.ProductId = 0;
            return View(model);
        }
        //[HttpPost]
        //public IActionResult Create(Product model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _Product.Add(model);
        //        return RedirectToAction("Index");
        //    }
        //    return View(model);
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(int Id,[Bind("ProductId,ProductName,Price,Description")] Product product,IFormFile imageFile) {
            if (Id != product.ProductId)
            {
                return NotFound();
            }
            if (ModelState.IsValid) {
                try {
                    if (imageFile != null) {
                        using (var ms = new MemoryStream()) {
                            imageFile.CopyTo(ms);
                            product.ProductImage = ms.ToArray();
                        }
                         _Product.Add(product);
                    }
                } catch (Exception ex) {
                    throw;
                }
            }
            return View(product);
        }
        public IActionResult Delete(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            else
            {
                return View(_Product.GetProduct(Id));
            }
            
        }
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int? Id) {
            _Product.Remove(Id);
            return RedirectToAction("Index");

        }
        public IActionResult Edit(int? Id)
        {
            var model = _Product.GetProduct(Id);
            return View("create", model);
        }

        //customer side 
        public IActionResult IndexCustomer() {
            if (HttpContext.Session.GetString("activeCustomer") != null && HttpContext.Session.GetString("activeBasket")!=null)
            {
                var loggedIn = JsonConvert.DeserializeObject<Customer>(HttpContext.Session.GetString("activeCustomer"));
                int customerID = Convert.ToInt32(loggedIn.CustomerId);
                string customerName = Convert.ToString(loggedIn.FirstName);
                ViewBag.cid = customerName;

                var currentBasket = JsonConvert.DeserializeObject<Basket>(HttpContext.Session.GetString("activeBasket"));
                int BasketId = Convert.ToInt32(currentBasket.BasketId);
                ViewBag.bid = BasketId;
                return View(_Product.GetProducts);
            }
            else
            {
                
                return RedirectToAction("CustomerLogin", "Customer");
            }
                
            
           
            

            
        }
        [HttpGet]
        public IActionResult DetailsCustomer(int? Id) {
            Product model = _Product.GetProduct(Id);
            ViewBag.selectedProduct = model;

            var loggedIn = JsonConvert.DeserializeObject<Customer>(HttpContext.Session.GetString("activeCustomer"));
            int customerID = Convert.ToInt32(loggedIn.CustomerId);
            string customerName = Convert.ToString(loggedIn.FirstName);
            ViewBag.cid = customerName;

            var currentBasket = JsonConvert.DeserializeObject<Basket>(HttpContext.Session.GetString("activeBasket"));
            int BasketId = Convert.ToInt32(currentBasket.BasketId);
            ViewBag.bid = BasketId;
            


            return View(model);
        }
    }
}

PetStore/Views/Product/Create.cshtml
@model PetStore.Models.Product

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <input asp-for="ProductId" class="form-control" type="hidden"/>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="ProductImage" class="control-label"></label>
                <input asp-for="ProductImage" class="form-control" />
                <span asp-validation-for="ProductImage" class="text-danger"></span>*@
                <div class="glyphicon-credit-card" style="width:15rem;">
                    <img class="img-responsive img-thumbnail img-rounded float-left"
                         src="data:image/jpeg;base64,@(Model.ProductImage == null ? "images/thumb.jpg" : Convert.ToBase64String(Model.ProductImage)) "/>

                </div>
                <div class="form-group">
                    <input asp-for="ProductImage" class="form-control" hidden />
                    <input name="imageFile" class="form-control" type="file" />
                </div>

                
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PetStore/Views/Product/Delete.cshtml
@model PetStore.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProductImage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductImage)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PetStore/Views/Product/DetailsCustomer.cshtml
@model PetStore.Models.Product

@{
    ViewData["Title"] = "DetailsCustomer";
}
<style>
    a:hover {
        color: orangered;
    }

    a.navRight {
        padding: 5px;
        border: 1px solid green;
    }
</style>
<div style="margin-top:20px;border:1px dotted gray;padding:30px;">
    <h2 style="display:inline">Welcome <b>@ViewBag.cid</b></h2>
    <a asp-action="getCustomerBasket" asp-controller="Basket">
        <img src="~/images/basket.png" height="50px" width="50px" style="float:right;" data-toggle="tooltip" title=@ViewBag.bid />
    </a>
    <div style="float:right;">

        <a asp-area="" asp-controller="Product" asp-action="IndexCustomer" style="text-decoration:none" class="navRight">Continue Shopping</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a asp-area="" asp-controller="Basket" asp-action="LoggedOut" style="text-decoration:none" class="navRight">Check out</a>
    </div>


</div>

<h3>@Html.DisplayFor(model => model.ProductName)</h3>
<div style="display:flex;flex-direction:row;justify-content:space-between">
    <div>
        <img class="img-responsive img-thumbnail rounded float-left" src="data:image/jpeg;base64,@(Model.ProductImage == null ? "" : Convert.ToBase64String(Model.ProductImage)) "
             onerror="this.onerror=null;this.src='../../images/thumb.jpg';" />
    </div>
    <div>
        @Html.DisplayFor(model => model.ProductName)<br />
        $ @Html.DisplayFor(model => model.Price)
    </div>
    <div>
        @Html.DisplayFor(model => model.Description)<br />
        <form asp-controller="BasketItem" asp-action="AddToCart" method="post">
            <input asp-for="basketItems.ItemQuantity" type="number" name="quantity" id="quantity" />
            <input asp-for="basketItems.ProductId" type="hidden" name="pid" id="pid" value="@Model.ProductId" />
            <input type="hidden" name="price" id="price" value="@Model.Price" />
            <button type="submit">Add to cart</button>
        </form>
        @Model.ProductName
    </div>
</div>

PetStore/Views/Product/Index.cshtml
@model IEnumerable<PetStore.Models.Product>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductImage)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            
            <td>
                <div class="card" style="width: 15rem;">
                    <img class="img-responsive img-thumbnail rounded float-left" src="data:image/jpeg;base64,@(item.ProductImage == null ? "" : Convert.ToBase64String(item.ProductImage)) " 
                         onerror="this.onerror=null;this.src='images/thumb.jpg';"/>
                </div>
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.ProductId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ProductId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ProductId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

PetStore/Views/Product/IndexCustomer.cshtml
@model IEnumerable<PetStore.Models.Product>

@{
    ViewData["Title"] = "IndexCustomer";
}


<div style="margin:20px">
    <h2 style="display:inline">Welcome <b>@ViewBag.cid</b></h2>
    <a asp-area="" asp-controller="Customer" asp-action="CustomerLogin" style="text-decoration:none;float:right;">Sign out</a>
    <a asp-action="getCustomerBasket" asp-controller="Basket">
        <img src="~/images/basket.png" height="50px" width="50px" style="float:right;margin-right:100px;" data-toggle="tooltip" title=@ViewBag.bid />
    </a>

</div>

<div style="display:flex;flex-direction:row;justify-content:space-around;align-content:center;flex-flow:wrap">

    @foreach (var item in Model)
    {
        <div style="display:flex;flex-direction:column;border:2px solid navy;padding:15px;margin:15px;">
            <div style="display:flex;flex-direction:row;justify-content:space-between"><span>@Html.DisplayFor(modelItem => item.ProductName)</span> <span>$@Html.DisplayFor(modelItem => item.Price)</span></div>
            <div class="card" style="width: 15rem;">
                <img class="img-responsive img-thumbnail rounded float-left" src="data:image/jpeg;base64,@(item.ProductImage == null ? "" : Convert.ToBase64String(item.ProductImage)) "
                     onerror="this.onerror=null;this.src='../images/thumb.jpg';" />
            </div>
            <div>
                <a asp-action="DetailsCustomer" asp-route-id="@item.ProductId" style="text-decoration:none">Details</a>
                @* this line is not working, review it later *@
                <a asp-action="AddToCart" asp-controller="BasketItem" asp-route-pid="@item.ProductId" asp-route-quantity=1 asp-route-price=0 style="text-decoration:none">
                    <img src="~/images/basket.png" style="width:20px;height:20px;float:right" />
                </a>
            </div>
        </div>
    }
</div>